In [1]:
import numpy as np

In [2]:
A=np.array([[1,1,-2],
           [3,2,-4],
            [2,-3,5]])
A

array([[ 1,  1, -2],
       [ 3,  2, -4],
       [ 2, -3,  5]])

In [3]:
n,m=A.shape[0],A.shape[1]
n,m

(3, 3)

In [5]:
U = A.copy()
L = np.eye(n)
for i in range(0,n):
    for j in range(i+1,n):
        multiplier = U[j,i] / U[i,i]
        U[j,:] = U[j,:] - multiplier * U[i,:]
        L[j,i] = multiplier
        
print("UPPER TRIANGULAR MATRIX:\n",U)
print()
print("LOWER TRIANGULAR MATRIX:\n",L)

UPPER TRIANGULAR MATRIX:
 [[ 1  1 -2]
 [ 0 -1  2]
 [ 0  0 -1]]

LOWER TRIANGULAR MATRIX:
 [[1. 0. 0.]
 [3. 1. 0.]
 [2. 5. 1.]]


## CHECKING IF THE OBTAINED L AND U MATRIX IS CORRECT

In [7]:
#CHECK
OriginalA = np.dot(L,U)
OriginalA

array([[ 1.,  1., -2.],
       [ 3.,  2., -4.],
       [ 2., -3.,  5.]])

## INVERSE OF THE MATRIX

In [8]:
n = L.shape[0]
Y = np.zeros((n, n))
X = np.zeros((n, n))
I = np.eye(n)
for col in range(n):  # Solve for each column of I
        for i in range(n):
            Y[i, col] = (I[i, col] - np.dot(L[i, :i], Y[:i, col])) / L[i, i]

for col in range(n):  # Solve for each column
        for i in range(n-1, -1, -1):
            X[i, col] = (Y[i, col] - np.dot(U[i, i+1:], X[i+1:, col])) / U[i, i]
X

array([[ -2.,   1.,   0.],
       [-23.,   9.,  -2.],
       [-13.,   5.,  -1.]])

## CHECKING IF THE INVERSE OBTAINED IS CORRECT

In [9]:
INV = np.dot(A,X)
INV

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## CHECKING UPPER AND LOWER TRIANGULAR MATRICES WITH STANDARD LIBRARY


In [10]:
from scipy.linalg import lu
P,Lower,Upper = lu(A)
print("UPPER TRIANGULAR MATRIX:\n",Upper)
print()
print("LOWER TRIANGULAR MATRIX:\n",Lower)

'''If you are using scipy.linalg.lu(A), it automatically applies 
row permutations, which changes the order of decomposition.'''

UPPER TRIANGULAR MATRIX:
 [[ 3.          2.         -4.        ]
 [ 0.         -4.33333333  7.66666667]
 [ 0.          0.         -0.07692308]]

LOWER TRIANGULAR MATRIX:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 0.33333333 -0.07692308  1.        ]]


'If you are using scipy.linalg.lu(A), it automatically applies \nrow permutations, which changes the order of decomposition.'

## CHECKING WITH STANDARD FUNCTION


In [11]:
INVL = np.linalg.inv(A)
INVL

array([[ -2.,   1.,   0.],
       [-23.,   9.,  -2.],
       [-13.,   5.,  -1.]])