## QR Decomposition without in built functions

In [1]:
import numpy as np

In [2]:
def gram_schmidt_q(A):
    A = np.array(A, dtype=np.float64)
    m, n = A.shape
    Q = np.zeros((m, n))
    for i in range(n):
        q = A[:, i].copy()
        for j in range(i):
            proj = np.dot(Q[:, j], A[:, i]) * Q[:, j]
            q -= proj
        norm_q = np.linalg.norm(q)
        Q[:, i] = q / norm_q
    return Q

In [3]:
def compute_r(A, Q):
    n = Q.shape[1]  
    R = np.zeros((n, n))  
    for i in range(n):  
        for j in range(i, n):
            R[i, j] = np.dot(Q[:, i], A[:, j])  
    return R

In [4]:
A = np.array([[1, 2, 4], [0, 0, 5], [0, 3, 6]], dtype=np.float64)
Q = gram_schmidt_q(A)
R = compute_r(A, Q)
print("Q (Orthonormal basis):")
print(Q)
print("\nR (Upper triangular matrix):")
print(R)

Q (Orthonormal basis):
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

R (Upper triangular matrix):
[[1. 2. 4.]
 [0. 3. 6.]
 [0. 0. 5.]]


In [5]:
B = np.dot(Q,R)
print(" Original Matrix")
print(B)

 Original Matrix
[[1. 2. 4.]
 [0. 0. 5.]
 [0. 3. 6.]]


## QR Decoposition using Built in function

In [8]:
A = np.array([[1, 2, 4], [0, 0, 5], [0, 3, 6]], dtype=np.float64)
Q,R = np.linalg.qr(A)
print("Q (Orthonormal basis):")
print(Q)
print("\nR (Upper triangular matrix):")
print(R)
C = np.dot(Q,R)
print(" Original Matrix")
print(C)

Q (Orthonormal basis):
[[ 1.  0.  0.]
 [-0.  0. -1.]
 [-0. -1.  0.]]

R (Upper triangular matrix):
[[ 1.  2.  4.]
 [ 0. -3. -6.]
 [ 0.  0. -5.]]
 Original Matrix
[[1. 2. 4.]
 [0. 0. 5.]
 [0. 3. 6.]]
